project_id = "kijwxiumskwztbjahuhv"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.send-recovery-code]
verify_jwt = false

[functions.verify-recovery-code]
verify_jwt = false

[functions.upgrade-to-provider]
verify_jwt = true
